name: CI/CD Security Pipeline for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }} # Update with your AWS region
  APPLICATION_NAME: "youtube-clone-app"
  ENVIRONMENT_NAME: "demo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Dependencies and Fix Vulnerabilities
      - name: Install Dependencies
        run: |
          npm install
          npm audit fix || echo "Ignoring vulnerabilities for now"
          npx update-browserslist-db@latest # Update Browserslist database

      # Step 3: Build the Application (Ignore Warnings in CI)
      - name: Build Application
        run: CI=false npm run build

      # Step 5: Archive the build for Elastic Beanstalk
      - name: Archive Build
        run: |
          mkdir -p eb-build
          cp -R src/ public/ .env package.json package-lock.json eb-build/
          zip -r eb-app.zip eb-build/

      # Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eb-app
          path: eb-app.zip 

      # Step 4: Start the Application
      - name: Start the Application
        run: npm start &
        env:
          PORT: 3000 # Ensure the app runs on the expected port

      - name: Wait for Application to Start
        run: |
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for app to start..."
            sleep 5
          done
      
      - name: Set proper permissions
        run: chmod -R 777 $(pwd)

      # Pull ZAP Docker Image
      - name: Pull ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:latest

      - name: Verify Rule File
        run: ls -l zap-rules.conf

      - name: Debug ZAP Container
        run: |
          docker run --rm --network host -v $(pwd):/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:latest ls -l /zap/wrk
     
      # Run OWASP ZAP Baseline Scan with Docker
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network host -v $(pwd):/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:latest zap-baseline.py \
            -t http://localhost:3000 \
            -r zap_report.html \
            -c /zap/wrk/zap-rules.conf \
            -d
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
          RULE_FILE_NAME: "zap-rules.conf"  # Name of the rule file
        #continue-on-error: true  # This will allow the pipeline to continue even if the scan fails
      
      # Upload ZAP Report as an Artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html


  static-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: static-analysis
    if: success()  # Deploy only if previous steps succeeded
    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: eb-app 
          
      # Step 4: Verify or Create S3 Bucket
      - name: Create S3 Bucket
        run: |
          if ! aws s3api head-bucket --bucket gyenoch-youtube-bucket 2>/dev/null; then
            aws s3api create-bucket \
              --bucket gyenoch-youtube-bucket \
              --region us-east-1 \
              --create-bucket-configuration LocationConstraint=us-east-1
          fi

      # Upload Zip file to S3 bucket
      - name: Upload Build to S3
        run: |
          aws s3 cp eb-app.zip s3://gyenoch-youtube-bucket/eb-app.zip
        
      # Step 3: Check if Elastic Beanstalk Application Exists
      - name: Check if Elastic Beanstalk Application Exists
        id: check-application
        run: |
          if aws elasticbeanstalk describe-applications --application-names $APPLICATION_NAME >/dev/null 2>&1; then
            echo "application_exists=true" >> $GITHUB_ENV
          else
            echo "application_exists=false" >> $GITHUB_ENV
          fi

      # Create EBS Application
      - name: Create Elastic Beanstalk Application
        if: env.application_exists == 'false'
        run: |
          aws elasticbeanstalk create-application \
            --application-name $APPLICATION_NAME \
            --description "Application for the YouTube clone app"

      # Check if Environment Exists
      - name: Check if Environment Exists
        id: check-environment
        run: |
          EXISTS=$(aws elasticbeanstalk describe-environments \
            --application-name $APPLICATION_NAME \
            --environment-names $ENVIRONMENT_NAME \
            --query 'Environments[0].EnvironmentName' \
            --output text --no-cli-pager 2>/dev/null || echo "NOT_FOUND")
          if [ "$EXISTS" == "$ENVIRONMENT_NAME" ]; then
            echo "environment_exists=true" >> $GITHUB_ENV
          else
            echo "environment_exists=false" >> $GITHUB_ENV
          fi
      
      - name: Debug - Check Environment Exists
        run: |
          echo "Environment Exists: ${{ env.environment_exists }}"
      
      # Create EBS Environment
      - name: Create Environment
        if: env.environment_exists == 'false'
        run: |
          aws elasticbeanstalk create-environment \
            --application-name $APPLICATION_NAME \
            --environment-name $ENVIRONMENT_NAME \
            --solution-stack-name "64bit Amazon Linux 2 v5.9.10 running Node.js 18" \
            --cname-prefix "youtube-clone-app" \
            --option-settings file://option-settings.json
      
      # Wait for Environment to be Ready
      - name: Wait for Environment to be Ready
        run: |
          MAX_RETRIES=30  # Maximum number of attempts
          RETRY_INTERVAL=10  # Time in seconds between retries
      
          for ((i=1; i<=MAX_RETRIES; i++)); do
            STATUS=$(aws elasticbeanstalk describe-environments \
              --environment-names $ENVIRONMENT_NAME \
              --query 'Environments[0].Status' \
              --output text)
      
            echo "Current status: $STATUS"
      
            if [[ "$STATUS" == "Ready" ]]; then
              echo "Environment is ready!"
              exit 0
            fi
      
            echo "Waiting for environment to be ready... ($i/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
          done
      
          echo "Environment failed to reach Ready state within the timeout period."
          exit 1
          

      # Step 3: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $APPLICATION_NAME \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=gyenoch-youtube-bucket,S3Key=eb-app.zip

          aws elasticbeanstalk update-environment \
            --environment-name $ENVIRONMENT_NAME \
            --version-label ${{ github.sha }}